version: '3'

services:
  fedb:
    image: "postgres"
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5430:5432
    networks:
      - lite-dev-network
  exporter-fe:
    env_file:
      - .env
    build: .
    volumes:
      - .:/app
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - fedb
    expose:
      - ${PORT}
    networks:
      - lite-dev-network
    command: pipenv run ./manage.py runserver 0.0.0.0:${PORT}

networks:
  lite-dev-network:
    external: false
