version: '3'

services:
  exfedb:
    image: "postgres"
    environment:
      - POSTGRES_PASSWORD=password
    command:
      - "postgres"
      - "-c"
      - "port=5430"
    ports:
      - 5430:5430
    networks:
      - lite-api_default
  exporter-fe:
    env_file:
      - .env
    build: .
    volumes:
      - .:/app
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - exfedb
    expose:
      - ${PORT}
    networks:
      - lite-api_default
    command: pipenv run ./manage.py runserver 0.0.0.0:${PORT}

networks:
  lite-api_default:
    external: true
