version: '3'

services:
  exfedb:
    image: "postgres"
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5430:5432
    networks:
      - lite-api_default

  exfe:
    env_file:
      - .env
    build: .
    volumes:
      - .:/app
    ports:
      - 9000:8080
    depends_on:
      - exfedb
    expose:
      - 8080
    networks:
      - lite-api_default
    command: pipenv run ./manage.py runserver 0.0.0.0:8080
#    use this command to use gunicorn rather than the django development server
#    command: pipenv run gunicorn -c gconfig.py -b 0.0.0.0:8080 --reload conf.wsgi

networks:
  lite-api_default:
    external: true
