# Generated by Django 2.2.3 on 2019-07-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='backend_id',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_token',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
