# Generated by Django 2.2.4 on 2019-08-20 12:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_lite_api_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organisation',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
