# Generated by Django 2.2.4 on 2019-11-14 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190829_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='organisation',
        ),
    ]
