ISO8601_FMT = "%Y-%m-%dT%H:%M:%S.%fZ"
NEWLINE = "\n"

# URLs
ACTIVITY_URL = "/activity/"
ORGANISATIONS_URL = "/organisations/"
EXPORTER_USERS_PERMISSIONS_URL = ORGANISATIONS_URL + "permissions/"
APPLICATIONS_URL = "/applications/"
APPLICATION_SUBMIT_URL = "/submit/"
CASES_URL = "/cases/"
GOODS_URL = "/goods/"
DOCUMENTS_URL = "/documents/"
PARTIES_URL = "/parties/"
DOCUMENT_URL = "/document/"
GOODSTYPES_URL = "/goodstypes/"
GOODSTYPE_URL = "/goodstype/"
GOODSTYPE_COUNTRY_URL = "assign-countries/"
USERS_URL = "/users/"
EXTERNAL_LOCATIONS_URL = "/external_locations/"
SITES_URL = "/sites/"
ROLES_URL = "/roles/"
NOTIFICATIONS_URL = USERS_URL + "notifications/"
CLC_NOTIFICATIONS_URL = USERS_URL + "clc-notifications/"
AUTHENTICATION_URL = USERS_URL + "authenticate/"
CASE_NOTES_URL = "/case-notes/"
ECJU_QUERIES_URL = "/ecju-queries/"
GENERATED_DOCUMENTS_URL = "/generated-documents/"
ADDITIONAL_DOCUMENT_URL = "/documents/"
MANAGE_STATUS_URL = "/status/"
DOCUMENT_SENSITIVITY_URL = "/document-sensitivity/"
EXISTING_PARTIES_URL = "/existing-parties"
COUNTRIES_URL = "/countries/"

# Queries URLs
QUERIES_URL = "/queries/"
GOODS_QUERY_URL = QUERIES_URL + "goods-queries/"
END_USER_ADVISORIES_URL = QUERIES_URL + "end-user-advisories/"

# Static URLs
STATIC_URL = "/static/"
STATUS_PROPERTIES_URL = STATIC_URL + "statuses/properties/"
UNITS_URL = STATIC_URL + "units/"
STATIC_COUNTRIES_URL = STATIC_URL + "countries/"
CONTROL_LIST_ENTRIES_URL = STATIC_URL + "control-list-entries/"
PV_GRADINGS_URL = STATIC_URL + "private-venture-gradings/"
MISSING_DOCUMENT_REASONS_URL = STATIC_URL + "missing-document-reasons/"

# Document URLs
DOWNLOAD_URL = "/download/"

# Applications constants
STANDARD_LICENCE = "standard_licence"
OPEN_LICENCE = "open_licence"
HMRC_QUERY = "hmrc_query"
EXHIBITION_CLEARANCE = "exhibition_clearance"
GIFTING_CLEARANCE = "gifting_clearance"
F680_CLEARANCE = "F680_clearance"

# Case type task list sections
CASE_SECTIONS = {
    "HMRC": HMRC_QUERY,
    "F680": F680_CLEARANCE,
    "HAS_LICENCE_TYPE": [STANDARD_LICENCE, OPEN_LICENCE],
    "HAS_TOLD_BY_OFFICIAL": [STANDARD_LICENCE],
    "HAS_GOODS": [STANDARD_LICENCE, EXHIBITION_CLEARANCE, GIFTING_CLEARANCE, F680_CLEARANCE],
    "HAS_GOODS_TYPES": [OPEN_LICENCE, HMRC_QUERY],
    "HAS_LOCATIONS": [STANDARD_LICENCE, OPEN_LICENCE, HMRC_QUERY, EXHIBITION_CLEARANCE],
    "HAS_COUNTRIES": OPEN_LICENCE,
    "HAS_END_USER": [STANDARD_LICENCE, EXHIBITION_CLEARANCE, F680_CLEARANCE, GIFTING_CLEARANCE],
    "HAS_ULTIMATE_END_USERS": [STANDARD_LICENCE, HMRC_QUERY, EXHIBITION_CLEARANCE],
    "HAS_CONSIGNEE": [STANDARD_LICENCE, HMRC_QUERY, EXHIBITION_CLEARANCE],
    "HAS_THIRD_PARTIES": [STANDARD_LICENCE, EXHIBITION_CLEARANCE, F680_CLEARANCE, GIFTING_CLEARANCE],
    "HAS_OPTIONAL_NOTE": [HMRC_QUERY],
    "HAS_NOTES": [STANDARD_LICENCE, OPEN_LICENCE, EXHIBITION_CLEARANCE, F680_CLEARANCE, GIFTING_CLEARANCE],
}

PERMANENT = "permanent"

APPLICANT_EDITING = "applicant_editing"

NOT_STARTED = "not_started"
IN_PROGRESS = "in_progress"
DONE = "done"

SUPER_USER_ROLE_ID = "00000000-0000-0000-0000-000000000003"
DEFAULT_USER_ROLE_ID = "00000000-0000-0000-0000-000000000004"

# CLC
UNSURE = "unsure"


class Permissions:
    EXPORTER_ADMINISTER_ROLES = "EXPORTER_ADMINISTER_ROLES"
    ADMINISTER_SITES = "ADMINISTER_SITES"
    ADMINISTER_USERS = "ADMINISTER_USERS"
    SUBMIT_CLEARANCE_APPLICATION = "SUBMIT_CLEARANCE_APPLICATION"
    SUBMIT_LICENCE_APPLICATION = "SUBMIT_LICENCE_APPLICATION"

    MANAGE_ORGANISATION_PERMISSIONS = [ADMINISTER_SITES, ADMINISTER_USERS, EXPORTER_ADMINISTER_ROLES]


class CaseType:
    APPLICATION = "application"
    GOODS_QUERY = "goods_query"
    EUA_QUERY = "end_user_advisory_query"
    HMRC_QUERY = "hmrc_query"
