from libraries.forms.components import Form, InputType, Question, HeadingStyle, Heading

new_site_form = Form(title='New Site', description='', caption='', questions=[
    Question(title='Name of site',
             description='',
             input_type=InputType.INPUT,
             name='name'),
    Heading('Address', HeadingStyle.M),
    Question(title='Address Line 1',
             description='',
             input_type=InputType.INPUT,
             name='address.address_line_1'),
    Question(title='Address Line 2',
             description='',
             input_type=InputType.INPUT,
             name='address.address_line_2',
             optional=True),
    Question(title='Zip code',
             description='',
             input_type=InputType.INPUT,
             name='address.zip_code'),
    Question(title='City',
             description='',
             input_type=InputType.INPUT,
             name='address.city'),
    Question(title='County',
             description='',
             input_type=InputType.INPUT,
             name='address.state'),
    Question(title='Country',
             description='',
             input_type=InputType.INPUT,
             name='address.country'),
])


edit_site_form = Form(title='Edit Site', description='', caption='', questions=[
    Question(title='Name of site',
             description='',
             input_type=InputType.INPUT,
             name='name',),
    Question(title='Address Line 1',
             description='',
             input_type=InputType.INPUT,
             name='part_number'),
    Question(title='Address Line 2',
             description='',
             input_type=InputType.INPUT,
             name='part_number',
             optional=True),
    Question(title='Post code',
             description='',
             input_type=InputType.INPUT,
             name='part_number'),
    Question(title='City',
             description='',
             input_type=InputType.INPUT,
             name='part_number'),
    Question(title='County',
             description='',
             input_type=InputType.INPUT,
             name='part_number'),
    Question(title='Email Address',
             description='',
             input_type=InputType.INPUT,
             name='part_number'),
    Question(title='Telephone Number',
             description='',
             input_type=InputType.INPUT,
             name='part_number'),
    Question(title='Contact Name',
             description='',
             input_type=InputType.INPUT,
             name='part_number'),
])
